<?php

declare(strict_types=1);

$finder = new PhpCsFixer\Finder()
    ->in([
        __DIR__.'/config',
        __DIR__.'/public',
        __DIR__.'/src',
        __DIR__.'/tests',
    ])
    // Auto-generated by Symfony (config reference for IDE autocompletion).
    // Formatting it would be undone on the next regeneration.
    ->notPath('reference.php')
    ->append([__FILE__]);

return new PhpCsFixer\Config()
    ->setFinder($finder)
    ->setRiskyAllowed(true)
    ->setRules([
        '@PER-CS' => true,
        '@PER-CS:risky' => true,
        '@Symfony' => true,
        '@Symfony:risky' => true,
        '@PHP85Migration' => true,
        // @PHP82Migration:risky is the newest risky migration set that exists;
        // there is no @PHP83/84/85Migration:risky.
        '@PHP82Migration:risky' => true,

        // Every PHP file declares strict types (see AGENTS.md).
        'declare_strict_types' => true,

        // Import global functions/constants instead of prefixing with a backslash
        // inline, so the use block documents what a file reaches for.
        'global_namespace_import' => [
            'import_classes' => true,
            'import_constants' => true,
            'import_functions' => true,
        ],
        'ordered_imports' => [
            'sort_algorithm' => 'alpha',
            'imports_order' => ['class', 'function', 'const'],
        ],
        'ordered_class_elements' => true,

        // Native types carry the information; PHPDoc that only repeats them is noise.
        'no_superfluous_phpdoc_tags' => [
            'allow_mixed' => true,
            'remove_inheritdoc' => true,
        ],
        'phpdoc_to_comment' => false,

        'native_function_invocation' => ['include' => ['@compiler_optimized'], 'scope' => 'namespaced'],
        'strict_comparison' => true,
        'strict_param' => true,
        'void_return' => true,
    ]);
